const gamesList = [
    {
        id: '1',
        group: 'A',
        round: '1',
        date: '2022-11-20T16:00Z',
        teams: ['qatar', 'ecuador'],
        times: ['Catar', 'Equador'],
        score: [0, 2],
        stadium: 'Estádio al-Bayt',
    },
    {
        id: '2',
        group: 'B',
        round: '1',
        date: '2022-11-21T13:00Z',
        teams: ['england', 'iran'],
        times: ['Inglaterra', 'Irã'],
        score: [6, 2],
        stadium: 'Estádio Internacional Khalifa',
    },
    {
        id: '3',
        group: 'A',
        round: '1',
        date: '2022-11-21T16:00Z',
        teams: ['senegal', 'netherlands'],
        times: ['Senegal', 'Holanda'],
        score: [0, 2],
        stadium: 'Estádio al-Thumama',
    },
    {
        id: '4',
        group: 'B',
        round: '1',
        date: '2022-11-21T19:00Z',
        teams: ['usa', 'wales'],
        times: ['EUA', 'Gales'],
        score: [1, 1],
        stadium: 'Estádio Ahmed bin Ali',
    },
    {
        id: '5',
        group: 'C',
        round: '1',
        date: '2022-11-22T10:00Z',
        teams: ['argentina', 'saudi-arabia'],
        times: ['Argentina', 'Arábia Saudita'],
        score: [1, 2],
        stadium: 'Estádio Lusail',
    },
    {
        id: '6',
        group: 'D',
        round: '1',
        date: '2022-11-22T13:00Z',
        teams: ['denmark', 'tunisia'],
        times: ['Dinamarca', 'Tunísia'],
        score: [0, 0],
        stadium: 'Estádio Education City',
    },
    {
        id: '7',
        group: 'C',
        round: '1',
        date: '2022-11-22T16:00Z',
        teams: ['mexico', 'poland'],
        times: ['México', 'Polônia'],
        score: [0, 0],
        stadium: 'Estádio 974',
    }, 
    {
        id: '8',
        group: 'D',
        round: '1',
        date: '2022-11-22T19:00Z',
        teams: ['france', 'australia'],
        times: ['França', 'Austrália'],
        score: [4, 1],
        stadium: 'Estádio al-Janoub',
    },
    {
        id: '9',
        group: 'F',
        round: '1',
        date: '2022-11-23T10:00Z',
        teams: ['morocco', 'croatia'],
        times: ['Marrocos', 'Croácia'],
        score: [0, 0],
        stadium: 'Estádio al-Bayt',
    },
    {
        id: '10',
        group: 'E',
        round: '1',
        date: '2022-11-23T13:00Z',
        teams: ['germany', 'japan'],
        times: ['Alemanha', 'Japão'],
        score: [1, 2],
        stadium: 'Estádio Internacional Khalifa',
    },
    {
        id: '11',
        group: 'E',
        round: '1',
        date: '2022-11-23T16:00Z',
        teams: ['spain', 'costa-rica'],
        times: ['Espanha', 'Costa Rica'],
        score: [7, 0],
        stadium: 'Estádio al-Thumama',
    },
    {
        id: '12',
        group: 'F',
        round: '1',
        date: '2022-11-23T19:00Z',
        teams: ['belgium', 'canada'],
        times: ['Bélgica', 'Canadá'],
        score: [1, 0],
        stadium: 'Estádio Ahmed bin Ali',
    },
    {
        id: '13',
        group: 'G',
        round: '1',
        date: '2022-11-24T10:00Z',
        teams: ['switzerland', 'cameroon'],
        times: ['Suíça', 'Camarões'],
        score: [1, 0],
        stadium: 'Estádio al-Janoub',
    },
    {
        id: '14',
        group: 'H',
        round: '1',
        date: '2022-11-24T13:00Z',
        teams: ['uruguay', 'korea'],
        times: ['Uruguai', 'Coréia do Sul'],
        score: [0, 0],
        stadium: 'Estádio Education City',
    },
    {
        id: '15',
        group: 'H',
        round: '1',
        date: '2022-11-24T16:00Z',
        teams: ['portugal', 'ghana'],
        times: ['Portugal', 'Gana'],
        score: [3, 2],
        stadium: 'Estádio 974',
    },
    {
        id: '16',
        group: 'G',
        round: '1',
        date: '2022-11-24T19:00Z',
        teams: ['brazil', 'serbia'],
        times: ['Brasil', 'Sérvia'],
        score: [2, 0],
        stadium: 'Estádio Lusail',
    },
    {
        id: '17',
        group: 'B',
        date: '2022-11-25T10:00Z',
        round: '2',
        teams: ['wales', 'iran'],
        times: ['Gales', 'Irã'],
        score: [0, 2],
        stadium: 'Estádio Ahmed bin Ali',
    },
    {
        id: '18',
        group: 'A',
        round: '2',
        date: '2022-11-25T13:00Z',
        teams: ['qatar', 'senegal'],
        times: ['Catar', 'Senegal'],
        score: [1, 3],
        stadium: 'Estádio al-Thumama',
    },
    {
        id: '19',
        group: 'A',
        round: '2',
        date: '2022-11-25T16:00Z',
        teams: ['netherlands', 'ecuador'],
        times: ['Holanda', 'Equador'],
        score: [1, 1],
        stadium: 'Estádio Internacional Khalifa',
    },
    {
        id: '20',
        group: 'B',
        round: '2',
        date: '2022-11-25T19:00Z',
        teams: ['england', 'usa'],
        times: ['Inglaterra', 'EUA'],
        score: [0, 0],
        stadium: 'Estádio al-Bayt',
    },
    {
        id: '21',
        group: 'D',
        round: '2',
        date: '2022-11-26T10:00Z',
        teams: ['tunisia', 'australia'],
        times: ['Tunísia', 'Austrália'],
        score: [0, 1],
        stadium: 'Estádio al-Janoub',
    },
    {
        id: '22',
        group: 'C',
        round: '2',
        date: '2022-11-26T13:00Z',
        teams: ['poland', 'saudi-arabia'],
        times: ['Polônia', 'Arábia Saudita'],
        score: [2, 0],
        stadium: 'Estádio Education City',
    },
    {
        id: '23',
        group: 'D',
        round: '2',
        date: '2022-11-26T16:00Z',
        teams: ['france', 'denmark'],
        times: ['França', 'Dinamarca'],
        score: [2, 1],
        stadium: 'Estádio 974',
    },
    {
        id: '24',
        group: 'C',
        round: '2',
        date: '2022-11-26T19:00Z',
        teams: ['argentina', 'mexico'],
        times: ['Argentina', 'México'],
        score: [2, 0],
        stadium: 'Estádio Lusail',
    },
    {
        id: '25',
        group: 'E',
        round: '2',
        date: '2022-11-27T10:00Z',
        teams: ['japan', 'costa-rica'],
        times: ['Japão', 'Costa Rica'],
        score: [0, 1],
        stadium: 'Estádio Ahmed bin Ali',
    },
    {
        id: '26',
        group: 'F',
        round: '2',
        date: '2022-11-27T13:00Z',
        teams: ['belgium', 'morocco'],
        times: ['Bélgica', 'Marrocos'],
        score: [0, 2],
        stadium: 'Estádio al-Thumama',
    },
    {
        id: '27',
        group: 'F',
        round: '2',
        date: '2022-11-27T16:00Z',
        teams: ['croatia', 'canada'],
        times: ['Croácia', 'Canadá'],
        score: [4, 1],
        stadium: 'Estádio Internacional Khalifa',
    },
    {
        id: '28',
        group: 'E',
        round: '2',
        date: '2022-11-27T19:00Z',
        teams: ['spain', 'germany'],
        times: ['Espanha', 'Alemanha'],
        score: [1, 1],
        stadium: 'Estádio al-Bayt',
    }, 
    {
        id: '29',
        group: 'G',
        round: '2',
        date: '2022-11-28T10:00Z',
        teams: ['cameroon', 'serbia'],
        times: ['Camarões', 'Sérvia'],
        score: [3, 3],
        stadium: 'Estádio al-Janoub',
    },
    {
        id: '30',
        group: 'H',
        round: '2',
        date: '2022-11-28T13:00Z',
        teams: ['korea', 'ghana'],
        times: ['Coréia do Sul', 'Gana'],
        score: [2, 3],
        stadium: 'Estádio Education City',
    }, 
    {
        id: '31',
        group: 'G',
        round: '2',
        date: '2022-11-28T16:00Z',
        teams: ['brazil', 'switzerland'],
        times: ['Brasil', 'Suíça'],
        score: [1, 0],
        stadium: 'Estádio 974',
    },
    {
        id: '32',
        group: 'H',
        round: '2',
        date: '2022-11-28T19:00Z',
        teams: ['portugal', 'uruguay'],
        times: ['Portugal', 'Uruguai'],
        score: [2, 0],
        stadium: 'Estádio Lusail',
    }, 
    {
        id: '33',
        group: 'A',
        date: '2022-11-29T15:00Z',
        round: '3',
        teams: ['netherlands', 'qatar'],
        times: ['Holanda', 'Catar'],
        score: [2, 0],
        stadium: 'Estádio al-Bayt',
    },
    {
        id: '34',
        group: 'A',
        round: '3',
        date: '2022-11-29T15:00Z',
        teams: ['ecuador', 'senegal'],
        times: ['Equador', 'Senegal'],
        score: [1, 2],
        stadium: 'Estádio Internacional Khalifa',
    },
    {
        id: '35',
        group: 'B',
        round: '3',
        date: '2022-11-29T19:00Z',
        teams: ['wales', 'england'],
        times: ['Gales', 'Inglaterra'],
        score: [0, 3],
        stadium: 'Estádio Ahmed bin Ali',
    },
    {
        id: '36',
        group: 'B',
        round: '3',
        date: '2022-11-29T19:00Z',
        teams: ['iran', 'usa'],
        times: ['Irã', 'EUA'],
        score: [0, 1],
        stadium: 'Estádio al-Thumama',
    },
    {
        id: '37',
        group: 'D',
        round: '3',
        date: '2022-11-30T15:00Z',
        teams: ['tunisia', 'france'],
        times: ['Tunísia', 'França'],
        score: [1, 0],
        stadium: 'Estádio Education City',
    },
    {
        id: '38',
        group: 'D',
        round: '3',
        date: '2022-11-30T15:00Z',
        teams: ['australia', 'denmark'],
        times: ['Austrália', 'Dinamarca'],
        score: [1, 0],
        stadium: 'Estádio al-Janoub',
    },
    {
        id: '39',
        group: 'C',
        round: '3',
        date: '2022-11-30T19:00Z',
        teams: ['poland', 'argentina'],
        times: ['Polônia', 'Argentina'],
        score: [0, 2],
        stadium: 'Estádio 974',
    },
    {
        id: '40',
        group: 'C',
        round: '3',
        date: '2022-11-30T19:00Z',
        teams: ['saudi-arabia', 'mexico'],
        times: ['Arábia Saudita', 'México'],
        score: [1, 2],
        stadium: 'Estádio Lusail',
    },
    {
        id: '41',
        group: 'F',
        round: '3',
        date: '2022-12-01T15:00Z',
        teams: ['croatia', 'belgium'],
        times: ['Croácia', 'Bélgica'],
        score: [0, 0],
        stadium: 'Estádio Ahmed bin Ali',
    },
    {
        id: '42',
        group: 'F',
        round: '3',
        date: '2022-12-01T15:00Z',
        teams: ['canada', 'morocco'],
        times: ['Canadá', 'Marrocos'],
        score: [1, 2],
        stadium: 'Estádio al-Thumama',
    },
    {
        id: '43',
        group: 'E',
        round: '3',
        date: '2022-12-01T19:00Z',
        teams: ['japan', 'spain'],
        times: ['Japão', 'Espanha'],
        score: [2, 1],
        stadium: 'Estádio Internacional Khalifa',
    }, 
    {
        id: '44',
        group: 'E',
        round: '3',
        date: '2022-12-01T19:00Z',
        teams: ['costa-rica', 'germany'],
        times: ['Costa Rica', 'Alemanha'],
        score: [2, 4],
        stadium: 'Estádio al-Bayt',
    },
    {
        id: '45',
        group: 'H',
        round: '3',
        date: '2022-12-02T15:00Z',
        teams: ['ghana', 'uruguay'],
        times: ['Gana', 'Uruguai'],
        score: [0, 2],
        stadium: 'Estádio al-Janoub',
    },
    {
        id: '46',
        group: 'H',
        round: '3',
        date: '2022-12-02T15:00Z',
        teams: ['korea', 'portugal',],
        times: ['Coréia do Sul', 'Portugal'],
        score: [2, 1],
        stadium: 'Estádio Education City',
    },
    {
        id: '47',
        group: 'G',
        round: '3',
        date: '2022-12-02T19:00Z',
        teams: ['serbia', 'switzerland'],
        times: ['Sérvia', 'Suíça'],
        score: [2, 3],
        stadium: 'Estádio 974',
    },
    {
        id: '48',
        group: 'G',
        round: '3',
        date: '2022-12-02T19:00Z',
        teams: ['cameroon', 'brazil'],
        times: ['Camarões', 'Brasil'],
        score: [1, 0],
        stadium: 'Estádio Lusail',
    },

    {
        id: '49',
        group: 'Oitavas de Finais',
        round: '4',
        date: '2022-12-03T15:00Z',
        teams: ['netherlands', 'usa'],
        times: ['Holanda', 'Estados Unidos'],
        score: [0, 0],
        stadium: 'Estádio Internacional Khalifa',
    },
    {
        id: '50',
        group: 'Oitavas de Finais',
        round: '4',
        date: '2022-12-03T19:00Z',
        teams: ['argentina', 'australia'],
        times: ['Argentina', 'Austrália'],
        score: [0, 0],
        stadium: 'Estádio Ahmed bin Ali',
    },
    {
        id: '51',
        group: 'Oitavas de Finais',
        round: '4',
        date: '2022-12-04T19:00Z',
        teams: ['england', 'senegal'],
        times: ['Inglaterra', 'Senegal'],
        score: [0, 0],
        stadium: 'Estádio Al Bayt',
    },
    {
        id: '52',
        group: 'Oitavas de Finais',
        round: '4',
        date: '2022-12-04T15:00Z',
        teams: ['france', 'poland'],
        times: ['França', 'Polônia'],
        score: [0, 0],
        stadium: 'Estádio Al Thumama',
    },
    {
        id: '53',
        group: 'Oitavas de Finais',
        round: '4',
        date: '2022-12-05T15:00Z',
        teams: ['japan', 'croatia'],
        times: ['Japão', 'Croácia'],
        score: [0, 0],
        stadium: 'Estádio Al Janoub',
    },
    {
        id: '54',
        group: 'Oitavas de Finais',
        round: '4',
        date: '2022-12-05T19:00Z',
        teams: ['brazil', 'korea'],
        times: ['Brasil', 'Coréia do Sul'],
        score: [0, 0],
        stadium: 'Estádio 974',
    },
    {
        id: '55',
        group: 'Oitavas de Finais',
        round: '4',
        date: '2022-12-06T15:00Z',
        teams: ['morocco', 'spain'],
        times: ['Marrocos', 'Espanha'],
        score: [0, 0],
        stadium: 'Estádio Education City',
    },
    {
        id: '56',
        group: 'Oitavas de Finais',
        round: '4',
        date: '2022-12-06T19:00Z',
        teams: ['portugal', 'switzerland'],
        times: ['Portugal', 'Suíça'],
        score: [0, 0],
        stadium: 'Estádio Lusail',
    },

    {
        id: '57',
        group: 'Quartas de Finais',
        round: '5',
        date: '2022-12-09T19:00Z',
        teams: ['', ''],
        times: ['', ''],
        score: [0, 0],
        stadium: 'Estádio Lusail',
    },
    {
        id: '58',
        group: 'Quartas de Finais',
        round: '5',
        date: '2022-12-09T15:00Z',
        teams: ['', ''],
        times: ['', ''],
        score: [0, 0],
        stadium: 'Estádio Education City',
    },
    {
        id: '59',
        group: 'Quartas de Finais',
        round: '5',
        date: '2022-12-10T19:00Z',
        teams: ['', ''],
        times: ['', ''],
        score: [0, 0],
        stadium: 'Estádio Al Bayt',
    },
    {
        id: '60',
        group: 'Quartas de Finais',
        round: '5',
        date: '2022-12-10T15:00Z',
        teams: ['', ''],
        times: ['', ''],
        score: [0, 0],
        stadium: 'Estádio Al Thumama',
    },

    {
        id: '61',
        group: 'Semi Finais',
        round: '6',
        date: '2022-12-13T19:00Z',
        teams: ['', ''],
        times: ['', ''],
        score: [0, 0],
        stadium: 'Estádio Lusail',
    },
    {
        id: '62',
        group: 'Semi Finais',
        round: '6',
        date: '2022-12-13T19:00Z',
        teams: ['', ''],
        times: ['', ''],
        score: [0, 0],
        stadium: 'Estádio Al Bayt',
    },

    {
        id: '63',
        group: 'Semi Finais',
        round: '7',
        date: '2022-12-17T15:00Z',
        teams: ['', ''],
        times: ['', ''],
        score: [0, 0],
        stadium: 'Estádio Khalifa International',
    },
    {
        id: '64',
        group: 'Semi Finais',
        round: '7',
        date: '2022-12-17T15:00Z',
        teams: ['', ''],
        times: ['', ''],
        score: [0, 0],
        stadium: 'Estádio Lusail',
    }
];

