export const gamesList = [
    {
        id: '1',
        date: '20/11/2022',
        time: '13:00',
        teams: ['qatar', 'ecuador'],
        times: ['Catar', 'Equador'],
        score: [0, 2],
        stadium: 'Estádio al-Bayt',
    },
    {
        id: '2',
        date: '21/11/2022',
        time: '10:00',
        teams: ['england', 'iran'],
        times: ['Inglaterra', 'Irã'],
        score: [6, 2],
        stadium: 'Estádio Internacional Khalifa',
    },
    {
        id: '3',
        date: '21/11/2022',
        time: '13:00',
        teams: ['senegal', 'netherlands'],
        times: ['Senegal', 'Holanda'],
        score: [0, 2],
        stadium: 'Estádio al-Thumama',
    },
    {
        id: '4',
        date: '21/11/2022',
        time: '16:00',
        teams: ['usa', 'wales'],
        times: ['EUA', 'Gales'],
        score: [1, 1],
        stadium: 'Estádio Ahmed bin Ali',
    },
    {
        id: '5',
        date: '22/11/2022',
        time: '07:00',
        teams: ['argentina', 'saudi-arabia'],
        times: ['Argentina', 'Arábia Saudita'],
        score: [1, 2],
        stadium: 'Estádio Lusail',
    },
    {
        id: '6',
        date: '22/11/2022',
        time: '10:00',
        teams: ['denmark', 'tunisia'],
        times: ['Dinamarca', 'Tunísia'],
        score: [0, 0],
        stadium: 'Estádio Education City',
    },
    {
        id: '7',
        date: '22/11/2022',
        time: '13:00',
        teams: ['mexico', 'poland'],
        times: ['México', 'Polônia'],
        score: [0, 0],
        stadium: 'Estádio 974',
    }, 
    {
        id: '8',
        date: '22/11/2022',
        time: '16:00',
        teams: ['france', 'australia'],
        times: ['França', 'Austrália'],
        score: [4, 1],
        stadium: 'Estádio al-Janoub',
    },
    {
        id: '9',
        date: '23/11/2022',
        time: '07:00',
        teams: ['morocco', ''],
        times: ['Marrocos', 'Croácia'],
        score: [0, 0],
        stadium: 'Estádio al-Bayt',
    },
    {
        id: '10',
        date: '23/11/2022',
        time: '10:00',
        teams: ['', ''],
        times: ['Alemanha', 'Japão'],
        score: [0, 0],
        stadium: 'Estádio Internacional Khalifa',
    },
    {
        id: '11',
        date: '23/11/2022',
        time: '13:00',
        teams: ['', ''],
        times: ['Espanha', 'Costa Rica'],
        score: [0, 0],
        stadium: 'Estádio al-Thumama',
    },
    {
        id: '12',
        date: '23/11/2022',
        time: '16:00',
        teams: ['belgium', 'canada'],
        times: ['Bélgica', 'Canadá'],
        score: [0, 0],
        stadium: 'Estádio Ahmed bin Ali',
    },
    {
        id: '13',
        date: '24/11/2022',
        time: '07:00',
        teams: ['switzerland', 'cameroon'],
        times: ['Suíça', 'Camarões'],
        score: [0, 0],
        stadium: 'Estádio al-Janoub',
    },
    {
        id: '14',
        date: '24/11/2022',
        time: '10:00',
        teams: ['uruguay', 'korea'],
        times: ['Uruguai', 'Coréia do Sul'],
        score: [0, 0],
        stadium: 'Estádio Education City',
    },
    {
        id: '15',
        date: '24/11/2022',
        time: '13:00',
        teams: ['portugal', 'ghana'],
        times: ['Portugal', 'Gana'],
        score: [0, 0],
        stadium: 'Estádio 974',
    },
    {
        id: '16',
        date: '24/11/2022',
        time: '16:00',
        teams: ['brazil', 'serbia'],
        times: ['Brasil', 'Sérvia'],
        score: [0, 0],
        stadium: 'Estádio Lusail',
    },
    {
        id: '17',
        date: '25/11/2022',
        time: '07:00',
        teams: ['wales', 'iran'],
        times: ['Gales', 'Irã'],
        score: [0, 0],
        stadium: 'Estádio Ahmed bin Ali',
    },
    {
        id: '18',
        date: '25/11/2022',
        time: '1:00',
        teams: ['qatar', 'senegal'],
        times: ['Catar', 'Senegal'],
        score: [0, 0],
        stadium: 'Estádio al-Thumama',
    },
    {
        id: '19',
        date: '25/11/2022',
        time: '13:00',
        teams: ['netherlands', 'ecuador'],
        times: ['Holanda', 'Equador'],
        score: [0, 0],
        stadium: 'Estádio Internacional Khalifa',
    },
    {
        id: '20',
        date: '25/11/2022',
        time: '16:00',
        teams: ['england', 'usa'],
        times: ['Inglaterra', 'EUA'],
        score: [0, 0],
        stadium: 'Estádio al-Bayt',
    },
    {
        id: '21',
        date: '26/11/2022',
        time: '07:00',
        teams: ['tunisia', 'australia'],
        times: ['Tunísia', 'Austrália'],
        score: [0, 0],
        stadium: 'Estádio al-Janoub',
    },
    {
        id: '22',
        date: '26/11/2022',
        time: '10:00',
        teams: ['poland', 'saudi-arabia'],
        times: ['Polônia', 'Arábia Saudita'],
        score: [0, 0],
        stadium: 'Estádio Education City',
    },
    {
        id: '23',
        date: '26/11/2022',
        time: '13:00',
        teams: ['france', 'denmark'],
        times: ['França', 'Dinamarca'],
        score: [0, 0],
        stadium: 'Estádio 974',
    },
    {
        id: '24',
        date: '26/11/2022',
        time: '16:00',
        teams: ['argentina', 'mexico'],
        times: ['Argentina', 'México'],
        score: [0, 0],
        stadium: 'Estádio Lusail',
    },
    {
        id: '25',
        date: '27/11/2022',
        time: '07:00',
        teams: ['japan', 'costa-rica'],
        times: ['Japão', 'Costa Rica'],
        score: [0, 0],
        stadium: 'Estádio Ahmed bin Ali',
    },
    {
        id: '26',
        date: '27/11/2022',
        time: '10:00',
        teams: ['belgium', 'morocco'],
        times: ['Bélgica', 'Marrocos'],
        score: [0, 0],
        stadium: 'Estádio al-Thumama',
    },
    {
        id: '27',
        date: '27/11/2022',
        time: '13:00',
        teams: ['croatia', 'canada'],
        times: ['Croácia', 'Canadá'],
        score: [0, 0],
        stadium: 'Estádio Internacional Khalifa',
    },
    {
        id: '28',
        date: '27/11/2022',
        time: '16:00',
        teams: ['spain', 'germany'],
        times: ['Espanha', 'Alemanha'],
        score: [0, 0],
        stadium: 'Estádio al-Bayt',
    }, 
    {
        id: '29',
        date: '28/11/2022',
        time: '07:00',
        teams: ['cameroon', 'serbia'],
        times: ['Camarões', 'Sérvia'],
        score: [0, 0],
        stadium: 'Estádio al-Janoub',
    },
    {
        id: '30',
        date: '28/11/2022',
        time: '10:00',
        teams: ['korea', 'ghana'],
        times: ['Coréia do Sul', 'Gana'],
        score: [0, 0],
        stadium: 'Estádio Education City',
    }, 
    {
        id: '31',
        date: '28/11/2022',
        time: '13:00',
        teams: ['brazil', 'switzerland'],
        times: ['Brasil', 'Suíça'],
        score: [0, 0],
        stadium: 'Estádio 974',
    },
    {
        id: '32',
        date: '28/11/2022',
        time: '16:00',
        teams: ['portugal', 'uruguay'],
        times: ['Portugal', 'Uruguai'],
        score: [0, 0],
        stadium: 'Estádio Lusail',
    }, 
    {
        id: '33',
        date: '29/11/2022',
        time: '12:00',
        teams: ['netherlands', 'qatar'],
        times: ['Holanda', 'Catar'],
        score: [0, 0],
        stadium: 'Estádio al-Bayt',
    },
    {
        id: '34',
        date: '29/11/2022',
        time: '12:00',
        teams: ['ecuador', 'senegal'],
        times: ['Equador', 'Senegal'],
        score: [0, 0],
        stadium: 'Estádio Internacional Khalifa',
    },
    {
        id: '35',
        date: '29/11/2022',
        time: '16:00',
        teams: ['wales', 'england'],
        times: ['Gales', 'Inglaterra'],
        score: [0, 0],
        stadium: 'Estádio Ahmed bin Ali',
    },
    {
        id: '36',
        date: '29/11/2022',
        time: '16:00',
        teams: ['iran', 'usa'],
        times: ['Irã', 'EUA'],
        score: [0, 0],
        stadium: 'Estádio al-Thumama',
    },
    {
        id: '37',
        date: '30/11/2022',
        time: '12:00',
        teams: ['tunisia', 'france'],
        times: ['Tunísia', 'França'],
        score: [0, 0],
        stadium: 'Estádio Education City',
    },
    {
        id: '38',
        date: '30/11/2022',
        time: '12:00',
        teams: ['australia', 'denmark'],
        times: ['Austrália', 'Dinamarca'],
        score: [0, 0],
        stadium: 'Estádio al-Janoub',
    },
    {
        id: '39',
        date: '30/11/2022',
        time: '16:00',
        teams: ['poland', 'argentina'],
        times: ['Polônia', 'Argentina'],
        score: [0, 0],
        stadium: 'Estádio 974',
    },
    {
        id: '40',
        date: '30/11/2022',
        time: '16:00',
        teams: ['saudi-arabia', 'mexico'],
        times: ['Arábia Saudita', 'México'],
        score: [0, 0],
        stadium: 'Estádio Lusail',
    },
    {
        id: '41',
        date: '01/12/2022',
        time: '12:00',
        teams: ['croatia', 'belgium'],
        times: ['Croácia', 'Bélgica'],
        score: [0, 0],
        stadium: 'Estádio Ahmed bin Ali',
    },
    {
        id: '42',
        date: '01/12/2022',
        time: '12:00',
        teams: ['canada', 'morocco'],
        times: ['Canadá', 'Marrocos'],
        score: [0, 0],
        stadium: 'Estádio al-Thumama',
    },
    {
        id: '43',
        date: '01/12/2022',
        time: '16:00',
        teams: ['japan', 'spain'],
        times: ['Japão', 'Espanha'],
        score: [0, 0],
        stadium: 'Estádio Internacional Khalifa',
    }, 
    {
        id: '44',
        date: '01/12/2022',
        time: '16:00',
        teams: ['costa-rica', 'germany'],
        times: ['Costa Rica', 'Alemanha'],
        score: [0, 0],
        stadium: 'Estádio al-Bayt',
    },
    {
        id: '45',
        date: '02/12/2022',
        time: '12:00',
        teams: ['ghana', 'uruguay'],
        times: ['Gana', 'Uruguai'],
        score: [0, 0],
        stadium: 'Estádio al-Janoub',
    },
    {
        id: '46',
        date: '02/12/2022',
        time: '12:00',
        teams: ['korea', 'portugal',],
        times: ['Coréia do Sul', 'Portugal'],
        score: [0, 0],
        stadium: 'Estádio Education City',
    },
    {
        id: '47',
        date: '02/12/2022',
        time: '16:00',
        teams: ['serbia', 'switzerland'],
        times: ['Sérvia', 'Suíça'],
        score: [0, 0],
        stadium: 'Estádio 974',
    },
    {
        id: '48',
        date: '02/12/2022',
        time: '16:00',
        teams: ['cameroon', 'brazil'],
        times: ['Camarões', 'Brasil'],
        score: [0, 0],
        stadium: 'Estádio Lusail',
    },
];